#!/usr/bin/env node

/**
 * intent init
 *
 * Scaffolds a new project with the full harness structure.
 * Run in an empty directory or the root of an existing repo.
 *
 * Usage:
 *   npx intent-harness init
 *   npx intent-harness narrate <id>
 *   npx intent-harness validate
 */

const fs = require("fs");
const path = require("path");
const readline = require("readline");
const { execSync } = require("child_process");

// Auto-load .env from cwd
const dotenvPath = path.join(process.cwd(), ".env");
if (fs.existsSync(dotenvPath)) {
  fs.readFileSync(dotenvPath, "utf8").split("\n").forEach(line => {
    const m = line.match(/^([A-Z_][A-Z0-9_]*)=(.*)$/);
    if (m && !process.env[m[1]]) process.env[m[1]] = m[2].replace(/^['"]|['"]$/g, "");
  });
}

const HARNESS_VERSION = "0.4.0";

// ─── Utils ───────────────────────────────────────────────────────────────────

function nanoid(len = 8) {
  const chars = "abcdefghijklmnopqrstuvwxyz0123456789";
  return Array.from({ length: len }, () => chars[Math.floor(Math.random() * chars.length)]).join("");
}

function ask(rl, question) {
  return new Promise((resolve) => rl.question(question, resolve));
}

function write(filePath, content) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content, "utf8");
  console.log(`  ✓ ${filePath}`);
}

function copyDir(src, dest) {
  if (!fs.existsSync(src)) return;
  fs.mkdirSync(dest, { recursive: true });
  for (const file of fs.readdirSync(src)) {
    const srcFile = path.join(src, file);
    const destFile = path.join(dest, file);
    if (fs.statSync(srcFile).isDirectory()) {
      copyDir(srcFile, destFile);
    } else {
      fs.copyFileSync(srcFile, destFile);
      console.log(`  ✓ ${destFile}`);
    }
  }
}

// ─── Init command ────────────────────────────────────────────────────────────

async function init() {
  console.log(`\nIntent Harness v${HARNESS_VERSION}`);
  console.log("──────────────────────────────────────\n");
  console.log("This will scaffold the requirement harness in the current directory.");
  console.log("It will not modify any existing files.\n");

  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });

  const productName = await ask(rl, "Product name: ");
  const githubOrg = await ask(rl, "GitHub org: ");
  const githubRepo = await ask(rl, "GitHub repo name: ");
  const designSystemRepo = await ask(rl, "Design system repo (org/repo): ");
  const primaryTeam = await ask(rl, "Primary team name: ");

  rl.close();

  const domainId = `dom_${nanoid()}`;
  const today = new Date().toISOString().split("T")[0];

  console.log("\nScaffolding harness...\n");

  // Directory structure
  const dirs = [
    "requirements/jobs",
    "requirements/domains",
    "requirements/design-principles",
    "requirements/design-specs",
    "requirements/requirements",
    "requirements/decisions",
    "schemas",
    ".intent/scripts",
    ".github/workflows",
  ];

  for (const dir of dirs) {
    fs.mkdirSync(dir, { recursive: true });
  }

  // intent.config.yml
  write(
    "intent.config.yml",
    `# intent.config.yml — generated by intent init
# Edit this file to configure the harness for your project.

product:
  name: "${productName}"
  description: ""

github:
  org: "${githubOrg}"
  repo: "${githubRepo}"

design-system:
  repo: "${designSystemRepo}"

teams:
  - name: ${primaryTeam.toLowerCase().replace(/\s+/g, "-")}
    github-team: "@${githubOrg}/${primaryTeam.toLowerCase().replace(/\s+/g, "-")}"
  - name: design-team
    github-team: "@${githubOrg}/design"

agents:
  spec:
    enabled: true
    max-clarifying-questions: 2
  decision:
    enabled: true
    issue-label: "decision-needed"
  trace:
    enabled: true
    include:
      - "src/**/*.ts"
      - "src/**/*.tsx"
      - "src/**/*.js"
    exclude:
      - "**/*.test.*"
      - "**/*.spec.*"
      - "**/node_modules/**"
  test:
    enabled: false

enforcement:
  warn-only: true
  unbuilt-warning-days: 30
`
  );

  // Initial domain record
  write(
    `requirements/domains/${domainId}.yaml`,
    `id: ${domainId}
type: domain
title: ${productName}
description: >
  Initial domain for ${productName}. Edit this to describe the domain's
  responsibilities and boundaries.
owner-team: ${primaryTeam.toLowerCase().replace(/\s+/g, "-")}
boundary:
  includes:
    - Edit this list to describe what belongs to this domain
  excludes:
    - Edit this list to describe what explicitly does not belong here
status:
  lifecycle: active
meta:
  created: "${today}"
  updated: "${today}"
`
  );

  // .intent/intent.lock
  write(
    ".intent/intent.lock",
    JSON.stringify({ version: HARNESS_VERSION, initialized: today }, null, 2)
  );

  // package.json for harness scripts
  write(
    ".intent/package.json",
    JSON.stringify(
      {
        name: "intent-harness-scripts",
        version: HARNESS_VERSION,
        private: true,
        scripts: {
          validate: "node scripts/validate.js",
          narrate: "node scripts/narrate.js",
        },
        dependencies: {
          ajv: "^8.12.0",
          "ajv-formats": "^2.1.1",
          "js-yaml": "^4.1.0",
        },
      },
      null,
      2
    )
  );

  console.log("\nInstalling script dependencies...");
  try {
    execSync("npm install", { cwd: ".intent", stdio: "inherit" });
  } catch (e) {
    console.log("  ⚠ npm install failed — run it manually in .intent/");
  }

  console.log(`
──────────────────────────────────────
✓ Harness initialized

Next steps:

  1. Add INTENT_API_KEY to your GitHub repo secrets
     (Settings → Secrets → Actions → New repository secret)

  2. Review and edit intent.config.yml with your team details

  3. Read INTENT.md — share it with everyone who will use this repo

  4. Open your first GitHub Issue to create your first job record
     The spec agent will draft the YAML for you

  5. When you're ready for hard enforcement, set enforcement.warn-only: false
     in intent.config.yml

Run locally:
  node .intent/scripts/validate.js          — validate all records
  node .intent/scripts/narrate.js <id>      — context for any record
  node .intent/scripts/narrate.js <id> --mode=domain  — domain overview

Domain created: ${domainId}
──────────────────────────────────────
`);
}

// ─── Upgrade ──────────────────────────────────────────────────────────────────

/**
 * intent upgrade
 *
 * Updates harness infrastructure files to the latest version.
 * NEVER touches requirement records or intent.config.yml.
 *
 * Infrastructure files that get updated:
 *   - schemas/*.json
 *   - scripts/ (all except intent.js itself)
 *   - .github/workflows/requirement-gate.yml
 *   - .github/workflows/spec-agent-*.yml
 *   - .github/workflows/trace-agent.yml
 *   - .github/workflows/decision-agent.yml
 *   - .github/workflows/test-agent.yml
 *   - .github/PULL_REQUEST_TEMPLATE.md
 *   - .intent/package.json (dependencies only)
 *
 * Records that are NEVER touched:
 *   - requirements/**
 *   - intent.config.yml
 *   - intent.lock
 */
async function upgrade() {
  console.log(`\nIntent Harness upgrade`);
  console.log("──────────────────────────────────────\n");

  const lockPath = path.join(process.cwd(), ".intent", "intent.lock");
  if (!fs.existsSync(lockPath)) {
    console.error("No intent.lock found. Is this a harness project? Run intent init first.");
    process.exit(1);
  }

  const lock = JSON.parse(fs.readFileSync(lockPath, "utf8"));
  const currentVersion = lock.version;

  console.log(`  Current version: ${currentVersion}`);
  console.log(`  Latest version:  ${HARNESS_VERSION}`);

  if (currentVersion === HARNESS_VERSION) {
    console.log("\n✓ Already at latest version.\n");
    process.exit(0);
  }

  // The upgrade source is the directory this script lives in,
  // which is the installed/linked version of the harness package.
  const pkgRoot = path.resolve(__dirname, "..");

  // Files to upgrade — never includes requirement records or config
  const INFRASTRUCTURE = [
    { src: "src/schemas/job.schema.json",             dst: "schemas/job.schema.json" },
    { src: "src/schemas/domain.schema.json",          dst: "schemas/domain.schema.json" },
    { src: "src/schemas/requirement.schema.json",     dst: "schemas/requirement.schema.json" },
    { src: "src/schemas/decision.schema.json",        dst: "schemas/decision.schema.json" },
    { src: "src/schemas/design-principle.schema.json",dst: "schemas/design-principle.schema.json" },
    { src: "src/schemas/design-spec.schema.json",     dst: "schemas/design-spec.schema.json" },
    { src: "src/validate.js",                 dst: ".intent/scripts/validate.js" },
    { src: "src/narrate.js",                  dst: ".intent/scripts/narrate.js" },
    { src: "src/flip-legitimacy.js",          dst: ".intent/scripts/flip-legitimacy.js" },
    { src: "src/review.js",                   dst: ".intent/scripts/review.js" },
    { src: "src/agents/spec-agent.js",        dst: ".intent/scripts/agents/spec-agent.js" },
    { src: "src/agents/trace-agent.js",       dst: ".intent/scripts/agents/trace-agent.js" },
    { src: "src/agents/decision-agent.js",    dst: ".intent/scripts/agents/decision-agent.js" },
    { src: "src/agents/test-agent.js",        dst: ".intent/scripts/agents/test-agent.js" },
    { src: "src/agents/ingest-agent.js",      dst: ".intent/scripts/agents/ingest-agent.js" },
    { src: "src/agents/lib/claude.js",        dst: ".intent/scripts/agents/lib/claude.js" },
    { src: "src/agents/lib/figma.js",         dst: ".intent/scripts/agents/lib/figma.js" },
    { src: "src/agents/lib/github.js",        dst: ".intent/scripts/agents/lib/github.js" },
    { src: "src/agents/lib/graph.js",         dst: ".intent/scripts/agents/lib/graph.js" },
    { src: "src/agents/lib/ids.js",           dst: ".intent/scripts/agents/lib/ids.js" },
    { src: "src/agents/lib/fetcher.js",       dst: ".intent/scripts/agents/lib/fetcher.js" },
    { src: "src/agents/lib/extractor.js",     dst: ".intent/scripts/agents/lib/extractor.js" },
    { src: ".github/workflows/requirement-gate.yml",   dst: ".github/workflows/requirement-gate.yml" },
    { src: ".github/workflows/spec-agent-issue.yml",   dst: ".github/workflows/spec-agent-issue.yml" },
    { src: ".github/workflows/spec-agent-pr.yml",      dst: ".github/workflows/spec-agent-pr.yml" },
    { src: ".github/workflows/spec-agent-post-merge.yml", dst: ".github/workflows/spec-agent-post-merge.yml" },
    { src: ".github/workflows/trace-agent.yml",        dst: ".github/workflows/trace-agent.yml" },
    { src: ".github/workflows/decision-agent.yml",     dst: ".github/workflows/decision-agent.yml" },
    { src: ".github/workflows/test-agent.yml",         dst: ".github/workflows/test-agent.yml" },
    { src: ".github/PULL_REQUEST_TEMPLATE.md",         dst: ".github/PULL_REQUEST_TEMPLATE.md" },
  ];

  const cwd = process.cwd();
  let updated = 0;
  let skipped = 0;

  for (const { src, dst } of INFRASTRUCTURE) {
    const srcPath = path.join(pkgRoot, src);
    const dstPath = path.join(cwd, dst);

    if (!fs.existsSync(srcPath)) {
      console.log(`  ⚠ Source not found: ${src}`);
      skipped++;
      continue;
    }

    fs.mkdirSync(path.dirname(dstPath), { recursive: true });
    fs.copyFileSync(srcPath, dstPath);
    console.log(`  ✓ ${dst}`);
    updated++;
  }

  // Update lock
  lock.version = HARNESS_VERSION;
  lock.lastUpgraded = new Date().toISOString().split("T")[0];
  fs.writeFileSync(lockPath, JSON.stringify(lock, null, 2));

  // Reinstall deps
  console.log("\nUpdating .intent dependencies...");
  try {
    execSync("npm install", { cwd: path.join(cwd, ".intent"), stdio: "inherit" });
  } catch {
    console.log("  ⚠ npm install failed — run it manually in .intent/");
  }

  console.log(`
──────────────────────────────────────
✓ Upgraded from ${currentVersion} → ${HARNESS_VERSION}

  Updated: ${updated} files
  Skipped: ${skipped} files

Your requirement records were not touched.
Review the workflow diffs before pushing to confirm nothing unexpected changed.
──────────────────────────────────────
`);
}

// ─── Router ──────────────────────────────────────────────────────────────────

const command = process.argv[2];

if (command === "init") {
  init().catch(console.error);
} else if (command === "upgrade") {
  upgrade().catch(console.error);
} else if (command === "validate") {
  process.argv = [process.argv[0], process.argv[1]];
  require("./validate.js");
} else if (command === "narrate") {
  process.argv = [process.argv[0], process.argv[1], ...process.argv.slice(3)];
  require("./narrate.js");
} else if (command === "trace") {
  process.argv = [process.argv[0], process.argv[1], "--mode=full"];
  require("./agents/trace-agent.js");
} else if (command === "test") {
  const reqArg = process.argv[3];
  if (reqArg && reqArg.startsWith("req_")) {
    process.argv = [process.argv[0], process.argv[1], "--mode=single", `--req=${reqArg}`];
  } else {
    process.argv = [process.argv[0], process.argv[1], "--mode=all"];
  }
  require("./agents/test-agent.js");
} else if (command === "decisions") {
  process.argv = [process.argv[0], process.argv[1], "--check=all"];
  require("./agents/decision-agent.js");
} else if (command === "ingest") {
  // Pass remaining args through to ingest agent
  process.argv = [process.argv[0], process.argv[1], ...process.argv.slice(3)];
  require("./agents/ingest-agent.js");
} else if (command === "review") {
  process.argv = [process.argv[0], process.argv[1], ...process.argv.slice(3)];
  require("./review.js");
} else if (command === "domains") {
  // List all domains — the thing a new team member runs first
  const path = require("path");
  const yaml = require("js-yaml");
  const { Graph } = require("./agents/lib/graph");
  const INTENT_ROOT = process.env.INTENT_ROOT || process.cwd();
  const graph = new Graph(path.join(INTENT_ROOT, "requirements"));
  const domains = graph.all("domain").filter((d) => d.status?.lifecycle === "active");

  if (domains.length === 0) {
    console.log("\nNo domains found. Run `intent init` or `intent ingest` to get started.\n");
  } else {
    console.log("\n── Domains ──────────────────────────────────────────────\n");
    domains.forEach((d) => {
      const reqs = graph.all("requirement").filter(
        (r) => r.domain === d.id && r.status?.lifecycle === "active"
      );
      const approved = reqs.filter((r) => r.status?.legitimacy === "approved").length;
      const proposed = reqs.filter((r) => r.status?.legitimacy === "proposed").length;
      const owner = d["owner-team"] || "unassigned";
      console.log(`  ${d.id}   ${d.title.padEnd(20)} ${owner.padEnd(20)} ${approved} approved, ${proposed} proposed`);
      console.log(`               ${d.description?.slice(0, 70) || ""}`);
      console.log();
    });
    console.log(`  Run: intent narrate <domain-id> --mode=domain   for full detail\n`);
  }
} else {
  console.log(`
Intent Harness v${HARNESS_VERSION}

Commands:
  intent init                          Scaffold a new project
  intent upgrade                       Update infrastructure to latest version
  intent domains                       List all domains (start here if you're new)
  intent validate                      Validate all requirement records
  intent narrate <id>                  Context narrative for any record
  intent narrate <id> --mode=domain    Full domain overview
  intent ingest --from=<sources>       Ingest existing documentation
  intent trace                         Full source scan and traceability update
  intent test [req_id]                 Generate acceptance criteria
  intent decisions                     Run conflict, gap, and revisit checks
  intent review                        Browse proposed records in the browser
  intent review --all                  Browse all records including approved
  intent review --domain=<id>          Limit review to one domain

Ingest examples:
  intent ingest --from=./docs/
  intent ingest --from=./spec.md,./notes.txt
  intent ingest --from=https://notion.so/your-page
  intent ingest --from=./docs/ --domain="Auth"   Process one domain only
  intent ingest --from=./docs/ --dry-run         Preview without committing
  cat spec.md | intent ingest

Environment variables:
  ANTHROPIC_API_KEY    Required for ingest, test, and spec agent commands
  FIGMA_ACCESS_TOKEN   Optional, enables Figma metadata in spec agent
  GITHUB_TOKEN         Required for opening PRs and issues
  GITHUB_REPOSITORY    owner/repo format
  INTENT_ROOT         Repo root (defaults to cwd)
`);
}
